const mongoose = require("mongoose");

module.exports = {
  mockUser: {
    username: "testuser",
    email: "testuser@example.com",
    password: "testpassword",
    isManager: false,
    xboxName: "TestXboxName",
    psName: "TestPSName",
    youtube: "TestYoutubeChannel",
    twitch: "TestTwitchChannel",
    playstation: "TestPlaystation",
    position: "TestPosition",
    membership: "TestMembership",
    profileImage: "https://example.com/testuser.jpg",
    leagues: [new mongoose.Types.ObjectId(), new mongoose.Types.ObjectId()],
    contractOffers: [
      new mongoose.Types.ObjectId(),
      new mongoose.Types.ObjectId(),
    ],
    trophies: {
      cleanSheets: 10,
      divisionEight: 1,
      divisionSeven: 0,
      divisionSix: 2,
      divisionFive: 4,
      divisionFour: 3,
      divisionThree: 5,
      divisionTwo: 6,
      divisionOne: 7,
      goldenBoot: 2,
      goldenGlove: 3,
      mostAssists: 4,
      mostHeaders: 5,
      mostIntercepts: 6,
      mostPasses: 7,
      mostTackles: 8,
      vgcdOr: 9,
    },
  },
  mockContract: {
    continent: "Europe",
    time: "2022-01-01T12:00:00.000Z",
    manager: "John Doe",
    console: "PlayStation 5",
    length: 12,
    divisionLogo: "https://example.com/division-logo.png",
    teamName: "exampleTeam",
  },
  mockLeague: {
    leagueName: "Test League",
    fixtures: [new mongoose.Types.ObjectId()],
    continent: "North America",
    division: 1,
    console: "Xbox",
    status: "Active",
    startDate: "2022-01-01",
    dates: ["2022-01-01", "2022-01-02"],
    times: ["19:00", "21:00"],
    rounds: 10,
    teamNames: ["Team 1", "Team 2"],
    teams: [new mongoose.Types.ObjectId(), new mongoose.Types.ObjectId()],
  },
  mockFixture: {
    home: "Team A",
    away: "Team B",
    week: 1,
    date: "2023-03-20",
    time: "13:00",
    lineupHome: [new mongoose.Types.ObjectId(), new mongoose.Types.ObjectId()],
    lineupAway: [new mongoose.Types.ObjectId(), new mongoose.Types.ObjectId()],
  },
  mockTeam: {
    name: "Team A",
    status: "Active",
    callTimes: 3,
    image: "https://example.com/team-a.png",
    liveLink: "https://example.com/team-a-live",
    continent: "Europe",
    leagueId: new mongoose.Types.ObjectId(),
    console: "Xbox",
    dates: ["2022-04-01", "2022-04-02"],
    times: ["19:00", "20:00"],
    registered: true,
    manager: "John Doe",
    managerId: new mongoose.Types.ObjectId(),
    roster: [new mongoose.Types.ObjectId(), new mongoose.Types.ObjectId()],
    lineup: [new mongoose.Types.ObjectId(), new mongoose.Types.ObjectId()],
  },
};
