const {
  createUser,
  readUser,
  readUsers,
  login,
  genericUpdate,
  updateLeague,
  updateContract,
  deleteUser,
} = require("./user");
const {
  createTeam,
  getTeamById,
  getTeams,
  updateTeam,
  updateRoster,
  updateLineup,
  deleteTeam,
} = require("./team");
const {
  createLeague,
  getAllLeagues,
  getLeagueById,
  updateLeagueGeneric,
  addFixtures,
  updateFixtures,
  updateTeams,
  deleteLeague,
} = require("./league");

module.exports = {
  createUser,
  readUser,
  readUsers,
  login,
  genericUpdate,
  updateLeague,
  updateContract,
  deleteUser,
  createTeam,
  getTeamById,
  getTeams,
  updateTeam,
  updateRoster,
  updateLineup,
  deleteTeam,
  createLeague,
  getAllLeagues,
  getLeagueById,
  updateLeagueGeneric,
  addFixtures,
  updateFixtures,
  updateTeams,
  deleteLeague,
};
